support chaining style, support .net standard 2.0/ 2.1 versions
invertedtomato/crc pull request #2
Opened 2021-01-13 13:17 UTC by Newp

2021-01-14 10:38 UTC, invertedtomato approved these changes

2021-01-14 10:38 UTC, invertedtomato approved these changes

2021-01-14 10:39 UTC, invertedtomato requested changes
I'd rather keep the example in the readme simple so people can readily get started.

2021-01-14 14:05 UTC, Newp commented
The readme file has been returned to it's original state.

2021-01-15 05:23 UTC, invertedtomato approved these changes

2021-01-15 05:24 UTC, merged

2021-01-15 05:24 UTC, invertedtomato commented
Thanks @Newp!